sudo: required
services: 
  - docker

addons:
  chrome: stable
  
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build -t ccpp888/sumzee -f Dockerfile.dev .

script: 
  - docker run ccpp888/sumzee npm run test