sudo: required
services: 
  - docker

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build -t ccpp888/sumzee -f Dockerfile.dev .

script: 
  - docker run ccpp888/sumzee npm run test